sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

before_install:
  - npm config set spin false
  - npm install -g typings

install:
  - typings install
  - npm install
