sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

script: npm test
before_install:
  - npm config set spin false
install:
  - node --version
  - npm --version
  - git --version
  - npm install
  - npm run build
